### ISSUE TITLE
Signature for no accedited people

### ISSUE THREAD

**Issue by ArthurChalard** [Azecko/epfl-email-signatures#61] opened 2024-01-29 15:48 UTC
When a person who has no specific accreditation enter his SCIPER, the signature keeps the phone number and the end of the signature from last search. Here is an example of the signature generated for me :

EPFL logo
Arthur Hugo Chalard
Student
IN-BA3
[Not defined](https://plan.epfl.ch/)
CH-1015 Lausanne
Phone: [+41 21 693 10 01](tel:+41216931001)
Mobile: [+41 79 XXX XX XX](tel:+4179XXXXXXX)
[martin.vetterli@epfl.ch](mailto:martin.vetterli@epfl.ch)
[mypage.epfl.ch](https://www.epfl.ch/)
[people/martin.vetterli](https://people.epfl.ch/107537)

Of course all the fields cannot be generated, but the email, and the people page could be.

**Comment by Azecko** [comment] 2024-01-30 15:07
Hi !

Thanks for your issue.
Normally, it should work now. Fixed by c06da30949cf4fe95e93801c7b09e414d0ec4b5a

Just let me know if the problem is still there ! ;)

**Closed as completed by Azecko** 2024-01-30 15:07 UTC
